services:
  rest_server:
    build:
      dockerfile: Dockerfile_Rest
    ports:
      - "8081:8081"
    depends_on:
      - ocr_server
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ELASTICSEARCH_HOST=elasticsearch
    networks:
      - spring-boot-network

  ocr_server:
    build:
      dockerfile: Dockerfile_OCR
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    privileged: true  # Required for Docker-in-Docker
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ELASTICSEARCH_HOST=elasticsearch
      - DOCKER_HOST=tcp://host.docker.internal:2375  # Set Docker host
    networks:
      - spring-boot-network


  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    networks:
      - spring-boot-network

  postgres_db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: dms_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dms_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - spring-boot-network

  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672" # Standard-AMQP-Port
      - "9093:15672" # Management-Webinterface
    environment:
      RABBITMQ_DEFAULT_USER: admin # Standard-Benutzername
      RABBITMQ_DEFAULT_PASS: admin # Standard-Passwort
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistente Daten
    networks:
      - spring-boot-network

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # S3-compatible API port
      - "9090:9090" # Web UI port (console)
    environment:
      MINIO_ROOT_USER: minioadmin # Set the admin username
      MINIO_ROOT_PASSWORD: minioadmin # Set the admin password
    command: server /data --console-address ":9090" # Specify console address
    volumes:
      - minio_data:/data
    networks:
      - spring-boot-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - cluster.name=paperless  # Set your desired cluster name
      - ELASTIC_USERNAME=elastic  # Set the default username
      - ELASTIC_PASSWORD=password  # Set the default password
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - spring-boot-network

volumes:
  db_data:
  rabbitmq_data:
  minio_data:

networks:
  spring-boot-network:
    driver: bridge
