services:
  spring-boot-app:
    build: ./
    container_name: spring-boot-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-network

networks:
  spring-boot-network:
    driver: bridge
