version: '3.8'
services:
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile_JavaApp
    container_name: spring-boot-server
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - spring-boot-network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - spring-boot-network

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: dms_db
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dms_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spring-boot-network

volumes:
  pgdata:

networks:
  spring-boot-network:
    driver: bridge
